apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  terminationGracePeriodSeconds: 2
  volumes:
  - name: nfs-sample
    nfs:
      server: 192.168.59.1
      path: /home/n0kt/Dropbox/tmp/shared
      readOnly: false
  containers:
  - name: container1
    image: nginx:latest
    volumeMounts:
    - name: nfs-sample
      mountPath: /opt/cnt
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do echo "$(date)" >> /opt/cnt/hello.txt; sleep 1; done']
    volumeMounts:
    - name: nfs-sample
      mountPath: /opt/cnt
