---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: dW1teXBhc3N3b3Jk  # "dummypassword" base64 encoded

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  mykey: mydata

---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
    - name: secret-volume
      mountPath: /etc/secret
  volumes:
  - name: config-volume
    configMap:
      name: myconfigmap
  - name: secret-volume
    secret:
      secretName: mysecret
