---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: demo
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube-m03

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: demo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mypod
  template:
    metadata:
      labels:
        app: mypod
    spec:
      volumes:
      - name: pvc-sample
        persistentVolumeClaim:
          claimName: mypvc
      containers:
        - name: container1
          image: nginx:latest
          volumeMounts:
          - name: pvc-sample
            mountPath: /opt
            subPath: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment02
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mypod
  template:
    metadata:
      labels:
        app: mypod
    spec:
      volumes:
      - name: pvc-sample
        persistentVolumeClaim:
          claimName: mypvc
      containers:
        - name: busybox
          image: busybox
          command: ['sh', '-c', 'while true; do echo "$(date)" >> /opt/hello-busybox.txt; sleep 1; done']
          volumeMounts:
          - name: pvc-sample
            mountPath: /opt
            subPath: busybox

