apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sample-eks3
  region: us-west-2
  version: "1.20"

fargateProfiles:
  - name: f-default
    selectors:
      - namespace: default
      - namespace: kube-system
  - name: f-jenkins
    selectors:
      - namespace: jenkins
  - name: f-dev
    selectors:
      - namespace: dev
