apiVersion: v1
kind: Pod
metadata:
  name: example-pod-with-init-container
spec:
  containers:
  - name: app-container
    image: nginx:latest
    ports:
    - containerPort: 80
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'echo We are fetching some configs for app-container! && sleep 5']
