baseURL = "https://www.darvein.net"
title = "Darvein"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "fruity"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsOptions = "tabWidth=2"
enableEmoji = true
#disqusShortname = "drv21"
ignorefiles = [ "venv", ".git" ]

[params]
author = "Dennis Ruiz"
description = "Dennis Ruiz's personal website"
keywords = "blog,developer,personal"
info = ["Full Stack", "Devops"]
avatarURL = "images/darvein-logo.webp"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2021
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/darvein/darvein.github.io/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 15
# Custom CSS
customCSS = ["css/custom.css"]
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
#customJS = ["js/custom.js"]
customJS = []
#mainSections = ["2024"]

[permalinks]
posts = "/:year/:month/:title/"

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud


# If you want to implement a Content-Security-Policy, add this section
[params.csp]
defaultsrc = ["'self'", "https://www.dropbox.com", "https://*.dl.dropboxusercontent.com", "https://photos.app.goo.gl", "https://drive.google.com", "https://photos.google.com", "https://video-downloads.googleusercontent.com", "https://*.googleusercontent.com", "https://*.googlevideo.com", "https://youtube.googleapis.com"]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'", "https://w.soundcloud.com", "https://www.youtube.com", "https://www.youtube-nocookie.com", "https://www.dropbox.com", "http://localhost", "https://www.dropbox.com", "http://halley.int", "https://disqus.com"]
imgsrc = ["'self'", "https://photos.google.com", "https://lh3.googleusercontent.com", "https://www.dropbox.com", "https://*.dl.dropboxusercontent.com", "https://*.disqus.com", "https://c.disquscdn.com"]
objectsrc = ["https://lh3.googleusercontent.com"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/",
  "https://c.disquscdn.com"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com", "https://cdnjs.cloudflare.com", "https://www.googletagmanager.com", "https://www.dropbox.com", "http://localhost", "http://halley.int", "https://drv21.disqus.com", "https://c.disquscdn.com"]
prefetchsrc = ["'self'", "https://youtube.googleapis.com"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com", "https://links.services.disqus.com"]

[taxonomies]
category = "categories"
subcategory = "subcategories"
series = "series"
tag = "tags"
author = "autores"

[[params.social]]
name = "Youtube"
icon = "fa fa-2x fa-youtube"
weight = 10
url = "https://www.youtube.com/@darvein"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 20
url = "https://twitter.com/darvein/"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 30
url = "https://github.com/darvein/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 40
url = "https://www.linkedin.com/in/darvein/"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 60
url = "https://darvein.github.io/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":us:"

#[[languages.en.menu.main]]
#name = "Infosec"
#url = "infosec/"
#weight = 10

#[[languages.en.menu.main]]
#name = "Coding"
#url = "coding/"
#weight = 20

#[[languages.en.menu.main]]
#name = "Devops"
#url = "devops/"
#weight = 30

#[[languages.en.menu.main]]
#name = "Digital"
#url = "digital/"
#weight = 40
