apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  volumes:
  - name: emptydir-sample
    emptyDir: 
      medium: Memory
  containers:
  - name: container1
    image: nginx:latest
    volumeMounts:
    - name: emptydir-sample
      mountPath: /opt
