---
apiVersion: v1
kind: Namespace
metadata:
  name: privileged-ns
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest

---
apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  namespace: privileged-ns
  labels:
    app: privileged-pod
spec:
  containers:
  - name: privileged-cnt
    image: nginx:latest
    securityContext:
      runAsUser: 0
      allowPrivilegeEscalation: true
    ports:
    - containerPort: 80
