# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/kinetic64"

  config.vm.define "bash_lab" do |box|
    box.vm.hostname = "worker"
    #box.vm.network :private_network, ip: "192.168.56.110"
  end
end
