---
apiVersion: v1
kind: Namespace
metadata:
  name: baseline-ns
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest

---
apiVersion: v1
kind: Pod
metadata:
  name: baseline-pod
  namespace: baseline-ns
  labels:
    app: baseline-pod
spec:
  hostNetwork: false # Here!
  containers:
  - name: baseline-cnt
    image: nginx:latest
    securityContext:
      privileged: false # HERE!
