apiVersion: batch/v1
kind: Job
metadata:
  name: job-demo
spec:
  template:
    spec:
      containers:
      - name: job-demo
        imagePullPolicy: Always
        image: registry.local:5000/job-demo:v1 
        env:
        - name: URL
          value: "http://frontend.default.local:31001/"
      restartPolicy: Never
  ttlSecondsAfterFinished: 3500
  backoffLimit: 30
  completions: 3
  parallelism: 2
  completionMode: Indexed
  #backoffLimitPerIndex: 1
  #maxFailedIndexes: 100
  podFailurePolicy:
    rules:
    - action: Ignore
      onExitCodes:
        operator: In
        values: [3]
    - action: FailJob
      onExitCodes:
        operator: In
        values: [2]
    - action: Ignore
      onPodConditions:
      - type: DisruptionTarget
