apiVersion: batch/v1
kind: Job
metadata:
  name: job-check
spec:
  template:
    spec:
      containers:
      - name: job-check
        imagePullPolicy: Always
        image: registry.local:5000/job-check:v1 
        env:
        - name: URL
          value: "http://frontend.default.local:31001/"
      restartPolicy: Never
  backoffLimit: 3
  ttlSecondsAfterFinished: 10
